"""add access_method column

Revision ID: 83116199874d
Revises: 8856b4361081
Create Date: 2025-11-15 21:17:12.761612

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '83116199874d'
down_revision: Union[str, Sequence[str], None] = '8856b4361081'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_policy_evaluations_id'), table_name='policy_evaluations')
    op.drop_table('policy_evaluations')
    op.drop_index(op.f('ix_cloud_accounts_id'), table_name='cloud_accounts')
    op.drop_index(op.f('ix_cloud_accounts_provider'), table_name='cloud_accounts')
    op.drop_table('cloud_accounts')
    op.drop_index(op.f('ix_policies_id'), table_name='policies')
    op.drop_index(op.f('ix_policies_provider'), table_name='policies')
    op.drop_table('policies')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_notifications_created_at'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_id'), table_name='notifications')
    op.drop_table('notifications')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notifications',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('title', sa.VARCHAR(length=255), nullable=False),
    sa.Column('message', sa.TEXT(), nullable=False),
    sa.Column('type', sa.VARCHAR(length=16), nullable=False),
    sa.Column('is_read', sa.BOOLEAN(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notifications_id'), 'notifications', ['id'], unique=False)
    op.create_index(op.f('ix_notifications_created_at'), 'notifications', ['created_at'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('email', sa.VARCHAR(length=255), nullable=False),
    sa.Column('full_name', sa.VARCHAR(length=255), nullable=False),
    sa.Column('hashed_password', sa.VARCHAR(length=255), nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=1)
    op.create_table('policies',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('provider', sa.VARCHAR(length=5), nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), nullable=False),
    sa.Column('control_id', sa.VARCHAR(length=255), nullable=False),
    sa.Column('category', sa.VARCHAR(length=255), nullable=False),
    sa.Column('severity', sa.VARCHAR(length=8), nullable=False),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider', 'control_id', name='uq_policy_provider_control')
    )
    op.create_index(op.f('ix_policies_provider'), 'policies', ['provider'], unique=False)
    op.create_index(op.f('ix_policies_id'), 'policies', ['id'], unique=False)
    op.create_table('cloud_accounts',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('provider', sa.VARCHAR(length=5), nullable=False),
    sa.Column('external_id', sa.VARCHAR(length=255), nullable=False),
    sa.Column('display_name', sa.VARCHAR(length=255), nullable=False),
    sa.Column('status', sa.VARCHAR(length=9), nullable=False),
    sa.Column('access_method', sa.VARCHAR(length=100), nullable=True),
    sa.Column('credential', sa.TEXT(), nullable=True),
    sa.Column('service_email', sa.VARCHAR(length=255), nullable=True),
    sa.Column('tenant_id', sa.VARCHAR(length=255), nullable=True),
    sa.Column('sync_frequency', sa.VARCHAR(length=50), nullable=False),
    sa.Column('auto_sync', sa.BOOLEAN(), nullable=False),
    sa.Column('last_synced_at', sa.DATETIME(), nullable=True),
    sa.Column('owner_id', sa.INTEGER(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider', 'external_id', name='uq_provider_account')
    )
    op.create_index(op.f('ix_cloud_accounts_provider'), 'cloud_accounts', ['provider'], unique=False)
    op.create_index(op.f('ix_cloud_accounts_id'), 'cloud_accounts', ['id'], unique=False)
    op.create_table('policy_evaluations',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('policy_id', sa.INTEGER(), nullable=False),
    sa.Column('account_id', sa.INTEGER(), nullable=False),
    sa.Column('status', sa.VARCHAR(length=13), nullable=False),
    sa.Column('last_checked_at', sa.DATETIME(), nullable=False),
    sa.Column('findings', sa.TEXT(), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['cloud_accounts.id'], ),
    sa.ForeignKeyConstraint(['policy_id'], ['policies.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('policy_id', 'account_id', name=op.f('uq_policy_account'))
    )
    op.create_index(op.f('ix_policy_evaluations_id'), 'policy_evaluations', ['id'], unique=False)
    # ### end Alembic commands ###
